# Site settings
title: "Прогрессор"
email:
description: "Блог прогрессора"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prgssr.ru" # the base hostname & protocol for your site
twitter_username: "@prgssr"
github_username:

# Build settings
kramdown:
  input: GFM
  auto_id_prefix: "heading-"
  enable_coderay: false
  toc_levels: 1..3
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

permalink: :categories/:title.html
exclude: [vendor, create.js]
keep_files: ["sonar-project.properties"]
highlighter: rouge
future: true

#collections
collections:
   documentation:
     output: true
     layout: doc
     date: "2015-07-28"
     thumbnail: "/images/jekyll.png"

#gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

#comments
disqus: prgssr

#analytics
google: "UA-64674967-1"

#defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: "documentation"
      type: documentation
    values:
      layout: doc
      thumbnail: "/images/jekyll.png"


#sass
sass:
  style: compact

#paginate
paginate: 10
