# Site settings
title: "Прогрессор"
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prgssr.ru" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
kramdown:
  input: GFM
permalink: :categories/:title.html
#collections
collections: 
   documentation: 
     output: true
     layout: post

#gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

#comments
disqus: prgssr

#analytics
google: "UA-64674967-1"