# Site settings
title: "Прогрессор"
email:
description: "Блог прогрессора"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prgssr.ru" # the base hostname & protocol for your site
twitter_username: "@prgssr"
github_username:

# Build settings
kramdown:
  input: GFM
  auto_id_prefix: "heading-"
  enable_coderay: false
permalink: :categories/:title.html
exclude: [vendor]

#collections
collections:
   documentation:
     output: true
     layout: doc
     date: "2015-07-28"
     image: "/images/jekyll.png"

#gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

#comments
disqus: prgssr

#analytics
google: "UA-64674967-1"

#defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      is_post: true

paginate: 10
